#!/usr/bin/env bash
# Display "To infinity and beyond" with sleep 2, handle SIGINT and SIGTERM
echo "$$" > /tmp/process_and_pid_file.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
