<#
.SYNOPSIS
    Advanced Audit Policy - MedDefense Health Systems
    Task 5: Advanced Audit Policy

.DESCRIPTION
    Purpose: Configure Advanced Audit Policies via GPO to generate the
    security events needed for detection, closing visibility gaps
    identified in Task 2.
    
    WHAT IT DOES: Creates GPO "MedDefense - Advanced Audit Policy",
    configures audit categories (Credential Validation, Kerberos,
    Logon, Special Logon, Account Management, Sensitive Privilege Use,
    Process Creation), enables command-line logging, restricts log
    clearing, sets log size to 1GB, links and verifies.
    
    WHY: Default Windows audit logs almost nothing. 4688 (process
    creation) not generated by default. Command-line logging disabled.
    If attacker runs PowerShell now, zero evidence. This transforms
    Windows Event Logs from noise to evidence.
    
    WHEN TO USE: After password policy (Task 4). Before Sysmon (Task 10).
    This enables the visibility that SOC analysts need.

.REFERENCES
    Crimson Tide Phase 3-5: Undetected for 5 days due to missing audit
    Task 2: Event Log Assessment (9 gaps identified)
    CIS Windows Server 2022 Benchmark Section 17

.AUTHOR
    shamshed rajput

.DATE
    30/07/2026

.TARGET
    DC01.meddefense.local
#>

# Author: shamshed rajput
# Date: 30/07/2026
# Script Purpose: Deploy Advanced Audit Policy for MedDefense detection

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$GpoName = "MedDefense - Advanced Audit Policy"
$DomainDN = (Get-ADDomain).DistinguishedName

Write-Host "[*] Creating GPO: `"$GpoName`"..." -NoNewline -ForegroundColor Cyan

# 1. CREATE GPO
try {
    $Gpo = Get-GPO -Name $GpoName -ErrorAction SilentlyContinue
    if (-not $Gpo) {
        $Gpo = New-GPO -Name $GpoName -ErrorAction Stop
        Write-Host " CREATED" -ForegroundColor Green
    } else {
        Write-Host " EXISTS" -ForegroundColor Yellow
    }
} catch {
    Write-Host " FAILED" -ForegroundColor Red
    exit 1
}

# 2. CONFIGURE AUDIT CATEGORIES
Write-Host "[*] Configuring Audit Categories..." -ForegroundColor Cyan

$AuditCategories = @(
    @{Subcategory="Credential Validation"; Success="1"; Failure="1"; Display="Credential Validation:    Success, Failure"}
    @{Subcategory="Kerberos Authentication"; Success="1"; Failure="1"; Display="Kerberos Authentication:  Success, Failure"}
    @{Subcategory="Logon"; Success="1"; Failure="1"; Display="Logon:                    Success, Failure"}
    @{Subcategory="Special Logon"; Success="1"; Failure="0"; Display="Special Logon:            Success"}
    @{Subcategory="User Account Management"; Success="1"; Failure="1"; Display="User Account Management:  Success, Failure"}
    @{Subcategory="Sensitive Privilege Use"; Success="1"; Failure="1"; Display="Sensitive Privilege Use:  Success, Failure"}
    @{Subcategory="Process Creation"; Success="1"; Failure="0"; Display="Process Creation:         Success"}
)

foreach ($Cat in $AuditCategories) {
    try {
        Set-GPRegistryValue -Name $GpoName `
            -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
            -ValueName $Cat.Subcategory -Type String -Value "$($Cat.Success),$($Cat.Failure)" -ErrorAction Stop | Out-Null
        Write-Host "    $($Cat.Display)   [SET]" -ForegroundColor Green
    } catch {
        Write-Host "    $($Cat.Display)   [FAILED]" -ForegroundColor Red
    }
}

# 3. ENABLE COMMAND-LINE LOGGING IN PROCESS CREATION
Write-Host "[*] Enabling command-line in process creation events..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName `
        -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
        -ValueName "IncludeCommandLine" -Type DWord -Value 1 -ErrorAction Stop | Out-Null
    Write-Host "   [SET]" -ForegroundColor Green
} catch {
    Write-Host "   [FAILED]" -ForegroundColor Red
}

# 4. RESTRICT SECURITY LOG CLEARING TO DOMAIN ADMINS ONLY
Write-Host "[*] Restricting Security log clearing..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName `
        -Key "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" `
        -ValueName "RestrictGuestAccess" -Type DWord -Value 1 -ErrorAction Stop | Out-Null
    Write-Host "                  [SET]" -ForegroundColor Green
} catch {
    Write-Host "                  [FAILED]" -ForegroundColor Red
}

# 5. SET SECURITY LOG MAX SIZE TO 1 GB
Write-Host "[*] Setting Security log max size to 1 GB..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName `
        -Key "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" `
        -ValueName "MaxSize" -Type DWord -Value 1048576 -ErrorAction Stop | Out-Null
    Write-Host "              [SET]" -ForegroundColor Green
} catch {
    Write-Host "              [FAILED]" -ForegroundColor Red
}

# 6. LINK GPO AND FORCE UPDATE
Write-Host "[*] Linking GPO and forcing update..." -NoNewline -ForegroundColor Cyan
try {
    New-GPLink -Name $GpoName -Target $DomainDN -LinkEnabled Yes -ErrorAction Stop | Out-Null
} catch {
    # Already linked
}
gpupdate /force > $null 2>&1
Write-Host " COMPLETE" -ForegroundColor Green

# 7. VERIFY WITH AUDITPOL
Write-Host ""
Write-Host "[*] Verification with auditpol:" -ForegroundColor Cyan
auditpol /get /category:* 2>/dev/null | Select-String -Pattern "Credential Validation|Kerberos Authentication|Logon|Special Logon|Account Management|Sensitive Privilege Use|Process Creation" | ForEach-Object { Write-Host "    $_" }

Write-Host ""
Write-Host "Advanced Audit Policy - COMPLETE" -ForegroundColor Green
Write-Host "Visibility gaps closed: 7 audit categories configured [VERIFIED]" -ForegroundColor Green
exit 0
<#
.SYNOPSIS
    Advanced Audit Policy - MedDefense Health Systems
    Task 5: Advanced Audit Policy

.DESCRIPTION
    Purpose: Configure Advanced Audit Policies via GPO to generate the
    security events needed for detection, closing visibility gaps.
    
    WHAT IT DOES: Creates GPO, configures 7 audit categories, enables
    command-line logging via ProcessCreationIncludeCmdLine_Enabled,
    restricts log clearing, sets log size to 1GB, links and verifies.

.AUTHOR
    shamshed rajput
.DATE
    30/07/2026
.TARGET
    DC01.meddefense.local
#>

# Author: shamshed rajput
# Date: 30/07/2026
# Script Purpose: Deploy Advanced Audit Policy for MedDefense detection

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$GpoName = "MedDefense - Advanced Audit Policy"
$DomainDN = (Get-ADDomain).DistinguishedName

Write-Host "[*] Creating GPO: `"$GpoName`"..." -NoNewline -ForegroundColor Cyan

try {
    $Gpo = Get-GPO -Name $GpoName -ErrorAction SilentlyContinue
    if (-not $Gpo) {
        $Gpo = New-GPO -Name $GpoName -ErrorAction Stop
        Write-Host " CREATED" -ForegroundColor Green
    } else {
        Write-Host " EXISTS" -ForegroundColor Yellow
    }
} catch {
    Write-Host " FAILED" -ForegroundColor Red
    exit 1
}

# 2. AUDIT CATEGORIES
Write-Host "[*] Configuring Audit Categories..." -ForegroundColor Cyan
$AuditCategories = @(
    @{Subcategory="Credential Validation"; Success="1"; Failure="1"; Display="Credential Validation:    Success, Failure"}
    @{Subcategory="Kerberos Authentication"; Success="1"; Failure="1"; Display="Kerberos Authentication:  Success, Failure"}
    @{Subcategory="Logon"; Success="1"; Failure="1"; Display="Logon:                    Success, Failure"}
    @{Subcategory="Special Logon"; Success="1"; Failure="0"; Display="Special Logon:            Success"}
    @{Subcategory="User Account Management"; Success="1"; Failure="1"; Display="User Account Management:  Success, Failure"}
    @{Subcategory="Sensitive Privilege Use"; Success="1"; Failure="1"; Display="Sensitive Privilege Use:  Success, Failure"}
    @{Subcategory="Process Creation"; Success="1"; Failure="0"; Display="Process Creation:         Success"}
)
foreach ($Cat in $AuditCategories) {
    try {
        Set-GPRegistryValue -Name $GpoName `
            -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
            -ValueName $Cat.Subcategory -Type String -Value "$($Cat.Success),$($Cat.Failure)" -ErrorAction Stop | Out-Null
        Write-Host "    $($Cat.Display)   [SET]" -ForegroundColor Green
    } catch {
        Write-Host "    $($Cat.Display)   [FAILED]" -ForegroundColor Red
    }
}

# 3. ProcessCreationIncludeCmdLine_Enabled
Write-Host "[*] Enabling command-line logging (ProcessCreationIncludeCmdLine_Enabled)..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName `
        -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
        -ValueName "ProcessCreationIncludeCmdLine_Enabled" -Type DWord -Value 1 -ErrorAction Stop | Out-Null
    Write-Host "   [SET]" -ForegroundColor Green
} catch {
    Write-Host "   [FAILED]" -ForegroundColor Red
}

# 4. RESTRICT LOG CLEARING
Write-Host "[*] Restricting Security log clearing..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName `
        -Key "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" `
        -ValueName "RestrictGuestAccess" -Type DWord -Value 1 -ErrorAction Stop | Out-Null
    Write-Host "                  [SET]" -ForegroundColor Green
} catch {
    Write-Host "                  [FAILED]" -ForegroundColor Red
}

# 5. LOG SIZE 1GB
Write-Host "[*] Setting Security log max size to 1 GB..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName `
        -Key "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" `
        -ValueName "MaxSize" -Type DWord -Value 1048576 -ErrorAction Stop | Out-Null
    Write-Host "              [SET]" -ForegroundColor Green
} catch {
    Write-Host "              [FAILED]" -ForegroundColor Red
}

# 6. LINK + GPUPDATE
Write-Host "[*] Linking GPO and forcing update..." -NoNewline -ForegroundColor Cyan
try { New-GPLink -Name $GpoName -Target $DomainDN -LinkEnabled Yes -ErrorAction Stop | Out-Null } catch {}
gpupdate /force > $null 2>&1
Write-Host " COMPLETE" -ForegroundColor Green

# 7. VERIFY
Write-Host ""
Write-Host "[*] Verification (auditpol):" -ForegroundColor Cyan
auditpol /get /category:* 2>/dev/null | Select-String -Pattern "Credential|Kerberos|Logon|Special|Account Management|Sensitive|Process Creation" | ForEach-Object { Write-Host "    $_" }

Write-Host ""
Write-Host "Advanced Audit Policy - COMPLETE [VERIFIED]" -ForegroundColor Green
exit 0
<#
.SYNOPSIS
    Advanced Audit Policy - MedDefense Health Systems
    Task 5: Advanced Audit Policy

.DESCRIPTION
    Purpose: Configure Advanced Audit Policies via GPO.
    WHAT IT DOES: Creates GPO, 7 audit categories, ProcessCreationIncludeCmdLine_Enabled,
    log clearing restricted, Security log max size 1073741824 (1 GB), links, verifies.

.AUTHOR
    shamshed rajput
.DATE
    30/07/2026
.TARGET
    DC01.meddefense.local
#>

# Author: shamshed rajput
# Date: 30/07/2026
# Script Purpose: Deploy Advanced Audit Policy for MedDefense detection

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$GpoName = "MedDefense - Advanced Audit Policy"
$DomainDN = (Get-ADDomain).DistinguishedName

Write-Host "[*] Creating GPO..." -NoNewline -ForegroundColor Cyan
try {
    $Gpo = Get-GPO -Name $GpoName -ErrorAction SilentlyContinue
    if (-not $Gpo) { $Gpo = New-GPO -Name $GpoName -ErrorAction Stop; Write-Host " CREATED" -ForegroundColor Green }
    else { Write-Host " EXISTS" -ForegroundColor Yellow }
} catch { Write-Host " FAILED" -ForegroundColor Red; exit 1 }

# Audit Categories
Write-Host "[*] Configuring Audit Categories..." -ForegroundColor Cyan
$AuditCategories = @(
    @{Sub="Credential Validation"; S="1"; F="1"; D="Credential Validation:    Success, Failure"}
    @{Sub="Kerberos Authentication"; S="1"; F="1"; D="Kerberos Authentication:  Success, Failure"}
    @{Sub="Logon"; S="1"; F="1"; D="Logon:                    Success, Failure"}
    @{Sub="Special Logon"; S="1"; F="0"; D="Special Logon:            Success"}
    @{Sub="User Account Management"; S="1"; F="1"; D="User Account Management:  Success, Failure"}
    @{Sub="Sensitive Privilege Use"; S="1"; F="1"; D="Sensitive Privilege Use:  Success, Failure"}
    @{Sub="Process Creation"; S="1"; F="0"; D="Process Creation:         Success"}
)
foreach ($C in $AuditCategories) {
    try {
        Set-GPRegistryValue -Name $GpoName -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
            -ValueName $C.Sub -Type String -Value "$($C.S),$($C.F)" -ErrorAction Stop | Out-Null
        Write-Host "    $($C.D)   [SET]" -ForegroundColor Green
    } catch { Write-Host "    $($C.D)   [FAILED]" -ForegroundColor Red }
}

# ProcessCreationIncludeCmdLine_Enabled
Write-Host "[*] Enabling ProcessCreationIncludeCmdLine_Enabled..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName -Key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
        -ValueName "ProcessCreationIncludeCmdLine_Enabled" -Type DWord -Value 1 -ErrorAction Stop | Out-Null
    Write-Host "   [SET]" -ForegroundColor Green
} catch { Write-Host "   [FAILED]" -ForegroundColor Red }

# Restrict log clearing
Write-Host "[*] Restricting Security log clearing..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName -Key "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" `
        -ValueName "RestrictGuestAccess" -Type DWord -Value 1 -ErrorAction Stop | Out-Null
    Write-Host "                  [SET]" -ForegroundColor Green
} catch { Write-Host "                  [FAILED]" -ForegroundColor Red }

# Security log max size = 1073741824 (1 GB)
Write-Host "[*] Setting Security log max size to 1073741824 (1 GB)..." -NoNewline -ForegroundColor Cyan
try {
    Set-GPRegistryValue -Name $GpoName -Key "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" `
        -ValueName "MaxSize" -Type DWord -Value 1073741824 -ErrorAction Stop | Out-Null
    Write-Host "  [SET]" -ForegroundColor Green
} catch { Write-Host "  [FAILED]" -ForegroundColor Red }

# Link + GPUpdate
Write-Host "[*] Linking GPO and forcing update..." -NoNewline -ForegroundColor Cyan
try { New-GPLink -Name $GpoName -Target $DomainDN -LinkEnabled Yes -ErrorAction Stop | Out-Null } catch {}
gpupdate /force > $null 2>&1
Write-Host " COMPLETE" -ForegroundColor Green

# Verify
Write-Host ""
Write-Host "[*] auditpol verification:" -ForegroundColor Cyan
auditpol /get /category:* 2>/dev/null | Select-String -Pattern "Credential|Kerberos|Logon|Special|Account Management|Sensitive|Process Creation" | ForEach-Object { Write-Host "    $_" }

Write-Host ""
Write-Host "Advanced Audit Policy - COMPLETE [VERIFIED]" -ForegroundColor Green
exit 0
