#!/bin/bash
set -euo pipefail

# ==============================================================================
# AUDIT ENGINE - MEDDEFENSE HEALTH SYSTEMS
# Task 10: The Audit Engine
# ==============================================================================
# WHAT IT DOES: Installs and configures auditd to monitor security-critical
#               events at the kernel level. Deploys custom rules for identity
#               files, privilege escalation, suspicious tools, and MedDefense
#               application files.
# WHY: Marcus Webb (1x00 incident): attacker moved undetected for 5 days.
#      Without auditd, there is no forensic trail. Crimson Tide Phase 5
#      specifically clears logs - auditd logs forwarded to log-srv-01
#      survive local clearing.
# ATTACKS BLOCKED: Crimson Tide Phase 2 (credential access detection),
#                  Phase 3 (privilege escalation detection),
#                  Phase 5 (defense evasion - logs survive clearing).
# ==============================================================================
# Analyst: shamshed rajput
# Date: 30/07/2026
# Target: billing-srv-01, web-srv-01, log-srv-01
# ==============================================================================

if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] Run with sudo."
    exit 1
fi

RULES_FILE="/etc/audit/rules.d/meddefense.rules"
RULES_APPLIED=0

# ------------------------------------------------------------------------------
# 1. INSTALL AND ENABLE auditd
# ------------------------------------------------------------------------------
echo "[*] Enabling auditd service..."

if ! dpkg -l auditd 2>/dev/null | grep -q "^ii"; then
    echo "    Installing auditd..."
    apt-get update -qq && apt-get install -y -qq auditd audispd-plugins
fi

systemctl enable auditd 2>/dev/null || true
systemctl restart auditd 2>/dev/null || true

if systemctl is-active --quiet auditd 2>/dev/null; then
    echo "    auditd.service: active (running)"
else
    echo "    [ERROR] auditd failed to start"
    exit 1
fi

# ------------------------------------------------------------------------------
# 2. DEPLOY MEDDEFENSE AUDIT RULES
# ------------------------------------------------------------------------------
echo "[*] Deploying MedDefense audit rules..."

cat > "${RULES_FILE}" << 'RULES_EOF'
# ==============================================================================
# MEDDEFENSE AUDIT RULES - Generated by 10-auditd_config.sh
# ==============================================================================
# Addresses: 1x00 crypto-miner incident (5 days undetected),
#            Crimson Tide Phase 2-3-5, CIS 4.1

# ----- IDENTITY FILES -----
# Monitor changes to user accounts and credentials (CT Phase 2)
-w /etc/passwd -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/gshadow -p wa -k identity

# ----- AUTHENTICATION CONFIG -----
# Monitor PAM and SSH config changes (CT Phase 5 defense evasion)
-w /etc/pam.d/ -p wa -k pam_config
-w /etc/ssh/sshd_config -p wa -k sshd_config

# ----- PRIVILEGE ESCALATION -----
# Monitor execution of privilege escalation tools (CT Phase 3)
-w /usr/bin/sudo -p x -k priv_esc
-w /usr/bin/su -p x -k priv_esc
-w /usr/bin/pkexec -p x -k priv_esc

# ----- SUDOERS -----
# Monitor sudoers configuration changes
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers

# ----- SUSPICIOUS TOOL EXECUTION -----
# Monitor download tools (CT Phase 3 - downloading exploits)
-w /usr/bin/wget -p x -k suspicious_download
-w /usr/bin/curl -p x -k suspicious_download

# Monitor netcat (reverse shell) usage
-w /usr/bin/nc -p x -k suspicious_netcat
-w /usr/bin/ncat -p x -k suspicious_netcat

# ----- MEDDEFENSE APPLICATION FILES -----
# Protect patient billing database files
-w /var/lib/mysql/ -p wa -k meddefense_db

# Protect web server configuration
-w /etc/apache2/ -p wa -k meddefense_web

# Protect startup scripts from tampering
-w /etc/init.d/ -p wa -k startup_scripts

# ----- KERNEL MODULE LOADING -----
# Monitor kernel module changes (rootkit detection)
-w /sbin/insmod -p x -k kernel_modules
-w /sbin/rmmod -p x -k kernel_modules
-w /sbin/modprobe -p x -k kernel_modules

# ----- CRON JOBS -----
# Monitor cron configuration changes (persistence detection)
-w /etc/crontab -p wa -k cron_jobs
-w /etc/cron.d/ -p wa -k cron_jobs
-w /var/spool/cron/crontabs/ -p wa -k cron_jobs

# ----- FAILED ACCESS ATTEMPTS -----
# Monitor failed file access attempts
-a always,exit -F arch=b64 -S open -F exit=-EACCES -k access_failed
-a always,exit -F arch=b64 -S open -F exit=-EPERM -k access_failed
RULES_EOF

echo "    $(wc -l < "${RULES_FILE}") lines written to ${RULES_FILE}"

# Display rules
grep "^\-w" "${RULES_FILE}" | while read -r rule; do
    path=$(echo "${rule}" | awk '{print $2}')
    key=$(echo "${rule}" | grep -oP '\-k \K\S+')
    printf "    %-50s" "${rule}"
    echo " [ADDED]"
    RULES_APPLIED=$((RULES_APPLIED + 1))
done

# Count syscall rules too
SYSCALL_RULES=$(grep "^\-a" "${RULES_FILE}" | wc -l)
RULES_APPLIED=$((RULES_APPLIED + SYSCALL_RULES))

# ------------------------------------------------------------------------------
# 3. LOAD RULES
# ------------------------------------------------------------------------------
echo "[*] Loading rules..."
augenrules --load > /dev/null 2>&1
echo "    augenrules --load: OK"

# ------------------------------------------------------------------------------
# 4. VERIFY RULES ARE ACTIVE
# ------------------------------------------------------------------------------
echo "[*] Verifying... auditctl -l:"
ACTIVE_RULES=$(auditctl -l 2>/dev/null | wc -l)
echo "    ${ACTIVE_RULES} rules loaded"

# ------------------------------------------------------------------------------
# 5. TEST AUDIT LOGGING
# ------------------------------------------------------------------------------
echo "[*] Test: reading /etc/shadow..."
cat /etc/shadow > /dev/null 2>&1 || true

# Small delay for auditd to write
sleep 1

EVENT_COUNT=$(ausearch -ts recent -k identity 2>/dev/null | grep -c "type=" || echo 0)

printf "    ausearch -ts recent -k identity: "
if [ "${EVENT_COUNT}" -gt 0 ]; then
    echo "${EVENT_COUNT} event(s) found [PASS]"
else
    echo "No events found [WARN - may need auditd restart]"
fi

# ------------------------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------------------------
echo ""
echo "======================================================================"
echo "  AUDIT ENGINE - COMPLETE"
echo "======================================================================"
echo "  Rules deployed: ${RULES_APPLIED}"
echo "  Active rules:   ${ACTIVE_RULES}"
echo "  Rules file:     ${RULES_FILE}"
echo "======================================================================"

exit 0#!/bin/bash
set -euo pipefail

# ==============================================================================
# AUDIT ENGINE - MEDDEFENSE HEALTH SYSTEMS
# Task 10: The Audit Engine
# ==============================================================================
# WHAT IT DOES: Installs and configures auditd to monitor security-critical
#               events at the kernel level. Deploys custom rules for identity
#               files, privilege escalation, suspicious tools, and MedDefense
#               application files.
# WHY: Marcus Webb (1x00 incident): attacker moved undetected for 5 days.
#      Without auditd, there is no forensic trail. Crimson Tide Phase 5
#      specifically clears logs - auditd logs forwarded to log-srv-01
#      survive local clearing.
# ATTACKS BLOCKED: Crimson Tide Phase 2 (credential access detection),
#                  Phase 3 (privilege escalation detection),
#                  Phase 5 (defense evasion - logs survive clearing).
# ==============================================================================
# Analyst: shamshed rajput
# Date: 30/07/2026
# Target: billing-srv-01, web-srv-01, log-srv-01
# ==============================================================================

if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] Run with sudo."
    exit 1
fi

RULES_FILE="/etc/audit/rules.d/meddefense.rules"
RULES_APPLIED=0

# ------------------------------------------------------------------------------
# 1. INSTALL AND ENABLE auditd
# ------------------------------------------------------------------------------
echo "[*] Enabling auditd service..."

if ! dpkg -l auditd 2>/dev/null | grep -q "^ii"; then
    echo "    Installing auditd..."
    apt-get update -qq && apt-get install -y -qq auditd audispd-plugins
fi

systemctl enable auditd 2>/dev/null || true
systemctl restart auditd 2>/dev/null || true

if systemctl is-active --quiet auditd 2>/dev/null; then
    echo "    auditd.service: active (running)"
else
    echo "    [ERROR] auditd failed to start"
    exit 1
fi

# ------------------------------------------------------------------------------
# 2. DEPLOY MEDDEFENSE AUDIT RULES
# ------------------------------------------------------------------------------
echo "[*] Deploying MedDefense audit rules..."

cat > "${RULES_FILE}" << 'RULES_EOF'
# ==============================================================================
# MEDDEFENSE AUDIT RULES - Generated by 10-auditd_config.sh
# ==============================================================================
# Addresses: 1x00 crypto-miner incident (5 days undetected),
#            Crimson Tide Phase 2-3-5, CIS 4.1

# ----- IDENTITY FILES -----
# Monitor changes to user accounts and credentials (CT Phase 2)
-w /etc/passwd -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/gshadow -p wa -k identity

# ----- AUTHENTICATION CONFIG -----
# Monitor PAM and SSH config changes (CT Phase 5 defense evasion)
-w /etc/pam.d/ -p wa -k pam_config
-w /etc/ssh/sshd_config -p wa -k sshd_config

# ----- PRIVILEGE ESCALATION -----
# Monitor execution of privilege escalation tools (CT Phase 3)
-w /usr/bin/sudo -p x -k priv_esc
-w /usr/bin/su -p x -k priv_esc
-w /usr/bin/pkexec -p x -k priv_esc

# ----- SUDOERS -----
# Monitor sudoers configuration changes
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers

# ----- SUSPICIOUS TOOL EXECUTION -----
# Monitor download tools (CT Phase 3 - downloading exploits)
-w /usr/bin/wget -p x -k suspicious_download
-w /usr/bin/curl -p x -k suspicious_download

# Monitor netcat (reverse shell) usage
-w /usr/bin/nc -p x -k suspicious_netcat
-w /usr/bin/ncat -p x -k suspicious_netcat

# ----- MEDDEFENSE APPLICATION FILES -----
# Protect patient billing database files
-w /var/lib/mysql/ -p wa -k meddefense_db

# Protect web server configuration
-w /etc/apache2/ -p wa -k meddefense_web

# Protect startup scripts from tampering
-w /etc/init.d/ -p wa -k startup_scripts

# ----- KERNEL MODULE LOADING -----
# Monitor kernel module changes (rootkit detection)
-w /sbin/insmod -p x -k kernel_modules
-w /sbin/rmmod -p x -k kernel_modules
-w /sbin/modprobe -p x -k kernel_modules

# ----- CRON JOBS -----
# Monitor cron configuration changes (persistence detection)
-w /etc/crontab -p wa -k cron_jobs
-w /etc/cron.d/ -p wa -k cron_jobs
-w /var/spool/cron/crontabs/ -p wa -k cron_jobs

# ----- FAILED ACCESS ATTEMPTS -----
# Monitor failed file access attempts
-a always,exit -F arch=b64 -S open -F exit=-EACCES -k access_failed
-a always,exit -F arch=b64 -S open -F exit=-EPERM -k access_failed
RULES_EOF

echo "    $(wc -l < "${RULES_FILE}") lines written to ${RULES_FILE}"

# Display rules
grep "^\-w" "${RULES_FILE}" | while read -r rule; do
    path=$(echo "${rule}" | awk '{print $2}')
    key=$(echo "${rule}" | grep -oP '\-k \K\S+')
    printf "    %-50s" "${rule}"
    echo " [ADDED]"
    RULES_APPLIED=$((RULES_APPLIED + 1))
done

# Count syscall rules too
SYSCALL_RULES=$(grep "^\-a" "${RULES_FILE}" | wc -l)
RULES_APPLIED=$((RULES_APPLIED + SYSCALL_RULES))

# ------------------------------------------------------------------------------
# 3. LOAD RULES
# ------------------------------------------------------------------------------
echo "[*] Loading rules..."
augenrules --load > /dev/null 2>&1
echo "    augenrules --load: OK"

# ------------------------------------------------------------------------------
# 4. VERIFY RULES ARE ACTIVE
# ------------------------------------------------------------------------------
echo "[*] Verifying... auditctl -l:"
ACTIVE_RULES=$(auditctl -l 2>/dev/null | wc -l)
echo "    ${ACTIVE_RULES} rules loaded"

# ------------------------------------------------------------------------------
# 5. TEST AUDIT LOGGING
# ------------------------------------------------------------------------------
echo "[*] Test: reading /etc/shadow..."
cat /etc/shadow > /dev/null 2>&1 || true

# Small delay for auditd to write
sleep 1

EVENT_COUNT=$(ausearch -ts recent -k identity 2>/dev/null | grep -c "type=" || echo 0)

printf "    ausearch -ts recent -k identity: "
if [ "${EVENT_COUNT}" -gt 0 ]; then
    echo "${EVENT_COUNT} event(s) found [PASS]"
else
    echo "No events found [WARN - may need auditd restart]"
fi

# ------------------------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------------------------
echo ""
echo "======================================================================"
echo "  AUDIT ENGINE - COMPLETE"
echo "======================================================================"
echo "  Rules deployed: ${RULES_APPLIED}"
echo "  Active rules:   ${ACTIVE_RULES}"
echo "  Rules file:     ${RULES_FILE}"
echo "======================================================================"

exit 0
