#!/bin/bash
set -euo pipefail

# ==============================================================================
# KERNEL SHIELD - VERSION COMPATIBLE KALI
# Task 5: The Kernel Shield
# ==============================================================================

SYSCTL_FILE="/etc/sysctl.d/99-meddefense-hardening.conf"
SYSCTL_CONF="/etc/sysctl.conf"
PASS=0
FAIL=0
APPLIED=0

if [ "$(id -u)" -ne 0 ]; then
    echo "[ERREUR] Lance avec sudo."
    exit 1
fi

# ------------------------------------------------------------------------------
# BACKUP
# ------------------------------------------------------------------------------
if [ -f "${SYSCTL_CONF}" ]; then
    SYSCTL_BACKUP="${SYSCTL_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
    echo "[*] Backing up ${SYSCTL_CONF}"
    cp "${SYSCTL_CONF}" "${SYSCTL_BACKUP}"
fi

mkdir -p /etc/sysctl.d

# ------------------------------------------------------------------------------
# BACKUP SI LE FICHIER EXISTE DÉJÀ
# ------------------------------------------------------------------------------
if [ -f "${SYSCTL_FILE}" ]; then
    SYSCTL_BACKUP="${SYSCTL_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
    echo "[*] Backing up ${SYSCTL_FILE} to ${SYSCTL_BACKUP}"
    cp "${SYSCTL_FILE}" "${SYSCTL_BACKUP}"
fi

# ------------------------------------------------------------------------------
# APPLY IMMEDIATELY
# ------------------------------------------------------------------------------
echo "[*] Applying settings..."
sysctl -p "${SYSCTL_FILE}" > /dev/null 2>&1
sysctl -p "${SYSCTL_CONF}" > /dev/null 2>&1 2>/dev/null || true
# ==============================================================================
# MEDDEFENSE KERNEL HARDENING - Generated by 5-sysctl_hardening.sh
# ==============================================================================
# Addresses: Crimson Tide Phase 4 (network pivot), Phase 5 (traffic redirect),
#            Phase 7 (DoS), 1x02-F026 (kernel CVEs)
# ==============================================================================

# ----- NETWORK STACK HARDENING -----
# Disable IP forwarding - prevents server from becoming a pivot point (CT Phase 4)
net.ipv4.ip_forward = 0

# Ignore ICMP redirects - prevents traffic redirection (CT Phase 5 MITM)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0

# Do not send ICMP redirects
net.ipv4.conf.all.send_redirects = 0

# Reject source-routed packets - prevents firewall bypass
net.ipv4.conf.all.accept_source_route = 0

# Log spoofed/martian packets - enables detection of suspicious traffic
net.ipv4.conf.all.log_martians = 1

# Enable SYN cookies - mitigates DoS attacks (CT Phase 7)
net.ipv4.tcp_syncookies = 1

# Ignore broadcast pings - prevents Smurf amplification attacks
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP errors
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Enable reverse path filtering - blocks IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# ----- IPv6 DISABLE -----
# Disable IPv6 if not used - reduces attack surface
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1

# ----- MEMORY PROTECTION -----
# Full ASLR (Address Space Layout Randomization) - makes exploits unreliable
kernel.randomize_va_space = 2

# Disable SUID core dumps - prevents information leakage
fs.suid_dumpable = 0

# Restrict kernel log access - prevents information gathering
kernel.dmesg_restrict = 1

# Hide kernel pointers - makes kernel exploits harder
kernel.kptr_restrict = 2
EOF

APPLIED=14

# ------------------------------------------------------------------------------
# APPLY IMMEDIATELY
# ------------------------------------------------------------------------------
echo "[*] Applying settings..."
sysctl --system > /dev/null 2>&1

# ------------------------------------------------------------------------------
# VERIFY EACH SETTING
# ------------------------------------------------------------------------------
echo ""

verify() {
    local param="$1"
    local expected="$2"
    local display="$3"
    local actual
    
    actual=$(sysctl -n "${param}" 2>/dev/null || echo "ERROR")
    
    printf "%-55s" "${display} = ${expected}"
    
    if [ "${actual}" = "${expected}" ]; then
        echo " [PASS]"
        PASS=$((PASS + 1))
    else
        echo " [FAIL] (got: ${actual})"
        FAIL=$((FAIL + 1))
    fi
}

verify "net.ipv4.ip_forward" "0" "net.ipv4.ip_forward"
verify "net.ipv4.conf.all.accept_redirects" "0" "net.ipv4.conf.all.accept_redirects"
verify "net.ipv4.conf.default.accept_redirects" "0" "net.ipv4.conf.default.accept_redirects"
verify "net.ipv4.conf.all.send_redirects" "0" "net.ipv4.conf.all.send_redirects"
verify "net.ipv4.conf.all.accept_source_route" "0" "net.ipv4.conf.all.accept_source_route"
verify "net.ipv4.conf.all.log_martians" "1" "net.ipv4.conf.all.log_martians"
verify "net.ipv4.tcp_syncookies" "1" "net.ipv4.tcp_syncookies"
verify "net.ipv4.icmp_echo_ignore_broadcasts" "1" "net.ipv4.icmp_echo_ignore_broadcasts"
verify "net.ipv6.conf.all.disable_ipv6" "1" "net.ipv6.conf.all.disable_ipv6"
verify "net.ipv6.conf.default.disable_ipv6" "1" "net.ipv6.conf.default.disable_ipv6"
verify "kernel.randomize_va_space" "2" "kernel.randomize_va_space"
verify "fs.suid_dumpable" "0" "fs.suid_dumpable"
verify "kernel.dmesg_restrict" "1" "kernel.dmesg_restrict"
verify "kernel.kptr_restrict" "2" "kernel.kptr_restrict"

# ------------------------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------------------------
echo ""
echo "======================================================================"
echo "  KERNEL SHIELD - COMPLETE"
echo "======================================================================"
echo "  Parameters applied: ${APPLIED}"
echo "  Verified PASS:      ${PASS}"
echo "  Verified FAIL:      ${FAIL}"
echo "  Config file:        ${SYSCTL_FILE}"
echo "======================================================================"

exit 0
